### PR TITLE
Added typesafe config options for setting some other cookie options

### PR DESCRIPTION
**Pull request by byrnedo**
Needed to add path and domain options for the session cookie, added secure and httpOnly as well.

This isn't 100% tested, but before I do, would you rather have the cookie stuff pulled out into a trait since stateless and stateful both use the same?

### CODE REVIEW

**Comment by satabin** [comment]
It indeed is a good idea, refactoring common code into a trait is of course a good solution.
Do you want to do it yourself or do you prefer me to push this refactoring into master before you rebase on it?

**Comment by byrnedo** [comment]
Hi Lucas,

Ok cool. No it's fine, I can do it on my fork for now. I'll need to bump 
versions and just so you're aware, I'm changing the config key from 
config-name to config.name etc, so this could be considered a breaking 
change??

**Comment by satabin** [comment]
No release was made yet, so there is no breaking changes.
Everything can be improved in any way that makes this library better.

**Comment by byrnedo** [comment]
Done as far as I can see.

**Comment by byrnedo** [comment]
Fair point. Will update.

**Comment by satabin** [comment]
It looks good, to me. A last point: maybe squash both commits together to keep a clean history, and I will merge it.
Thanks for contributing

**Comment by byrnedo** [comment]
Those are squashed now. No problem, thanks for the really useful project!

**Pull request merged**
